name: Get Domain Details

on: 
  workflow_dispatch:
    inputs:
      hostname: 
        description:
        required: true
        default: github.com
      port:
        description:
        required: false
        default: 443

jobs:
  get_domain_details:
    runs-on: ubuntu-latest

    steps: 
      - name: Get Domain details
        id: check
        uses: jmtellez/domain-cert-checker@v1.0.1
        with:
          hostname: ${{ github.event.inputs.hostname }}
          port: ${{ github.event.inputs.port }}

      - name: Print details
        run: |
          echo toJSON(${{ steps.check.outputs.details }})
          echo "toJSON(${{ steps.check.outputs.details }})" >> $GITHUB_STEP_SUMMARY
